Traceback (most recent call last):
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
rmpx6bit_env = gym.make('real-multiplexer-6bit-v0')
random_state = rmpx6bit_env.reset()

threshold = 0.5  # secret knowledge

t = HTML(tabulate([
    ['<b>rMPX</b>'] + [round(s, 2) for s in random_state],
    ['<b>MPX</b>'] + list(map(lambda x: 1 if x > threshold else 0, random_state))
], tablefmt='unsafehtml'))

glue('rmpx_mpx_mapping_table', t, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/gym/envs/registration.py:158[0m, in [0;36mEnvRegistry.spec[0;34m(self, path)[0m
[1;32m    157[0m [38;5;28;01mtry[39;00m:
[0;32m--> 158[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43menv_specs[49m[43m[[49m[38;5;28;43mid[39;49m[43m][49m
[1;32m    159[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:
[1;32m    160[0m     [38;5;66;03m# Parse the env name and check to see if it matches the non-version[39;00m
[1;32m    161[0m     [38;5;66;03m# part of a valid env (could also check the exact number here)[39;00m

[0;31mKeyError[0m: 'real-multiplexer-6bit-v0'

During handling of the above exception, another exception occurred:

[0;31mUnregisteredEnv[0m                           Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m rmpx6bit_env [38;5;241m=[39m [43mgym[49m[38;5;241;43m.[39;49m[43mmake[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mreal-multiplexer-6bit-v0[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m random_state [38;5;241m=[39m rmpx6bit_env[38;5;241m.[39mreset()
[1;32m      4[0m threshold [38;5;241m=[39m [38;5;241m0.5[39m  [38;5;66;03m# secret knowledge[39;00m

File [0;32m~/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/gym/envs/registration.py:235[0m, in [0;36mmake[0;34m(id, **kwargs)[0m
[1;32m    234[0m [38;5;28;01mdef[39;00m [38;5;21mmake[39m([38;5;28mid[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m--> 235[0m     [38;5;28;01mreturn[39;00m [43mregistry[49m[38;5;241;43m.[39;49m[43mmake[49m[43m([49m[38;5;28;43mid[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/gym/envs/registration.py:128[0m, in [0;36mEnvRegistry.make[0;34m(self, path, **kwargs)[0m
[1;32m    126[0m [38;5;28;01melse[39;00m:
[1;32m    127[0m     logger[38;5;241m.[39minfo([38;5;124m"[39m[38;5;124mMaking new env: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, path)
[0;32m--> 128[0m spec [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mspec[49m[43m([49m[43mpath[49m[43m)[49m
[1;32m    129[0m env [38;5;241m=[39m spec[38;5;241m.[39mmake([38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    130[0m [38;5;28;01mreturn[39;00m env

File [0;32m~/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/gym/envs/registration.py:203[0m, in [0;36mEnvRegistry.spec[0;34m(self, path)[0m
[1;32m    197[0m     [38;5;28;01mraise[39;00m error[38;5;241m.[39mUnregisteredEnv(
[1;32m    198[0m         [38;5;124m"[39m[38;5;124mToytext environment [39m[38;5;132;01m{}[39;00m[38;5;124m has been moved out of Gym. Install it via `pip install gym-legacy-toytext` and add `import gym_toytext` before using it.[39m[38;5;124m"[39m[38;5;241m.[39mformat(
[1;32m    199[0m             [38;5;28mid[39m
[1;32m    200[0m         )
[1;32m    201[0m     )
[1;32m    202[0m [38;5;28;01melse[39;00m:
[0;32m--> 203[0m     [38;5;28;01mraise[39;00m error[38;5;241m.[39mUnregisteredEnv([38;5;124m"[39m[38;5;124mNo registered env with id: [39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat([38;5;28mid[39m))

[0;31mUnregisteredEnv[0m: No registered env with id: real-multiplexer-6bit-v0
UnregisteredEnv: No registered env with id: real-multiplexer-6bit-v0

