Traceback (most recent call last):
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/arc/miniconda3/envs/real-valued-acs-system/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import logging

logging.basicConfig(level=logging.WARN, format='%(relativeCreated)6d %(threadName)s %(message)s')

import gym
from typing import List
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

import pathlib
from src.decorators import repeat, get_from_cache_or_run
from src.metrics import parse_experiments_results

from lcs.agents.acs2 import Configuration, ACS2
from lcs.metrics import population_metrics
from lcs.strategies.action_selection import EpsilonGreedy, ActionDelay, KnowledgeArray

plt.ioff() # turn off interactive plotting

cache_dir = f'{pathlib.Path().absolute()}/cache'
plot_dir = f'{pathlib.Path().absolute()}/plots'
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/tmp/ipykernel_333881/3695721014.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0;32mimport[0m [0mpathlib[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0;32mfrom[0m [0msrc[0m[0;34m.[0m[0mdecorators[0m [0;32mimport[0m [0mrepeat[0m[0;34m,[0m [0mget_from_cache_or_run[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m [0;32mfrom[0m [0msrc[0m[0;34m.[0m[0mmetrics[0m [0;32mimport[0m [0mparse_experiments_results[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m [0;34m[0m[0m
[1;32m     15[0m [0;32mfrom[0m [0mlcs[0m[0;34m.[0m[0magents[0m[0;34m.[0m[0macs2[0m [0;32mimport[0m [0mConfiguration[0m[0;34m,[0m [0mACS2[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Projects/pwr/phd/book/chapters/4_biased_exploration/../../../src/metrics.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mfrom[0m [0mlcs[0m [0;32mimport[0m [0mPerception[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'lcs'
ModuleNotFoundError: No module named 'lcs'

